#!/usr/bin/env bash
# =============================================================================
# VPS Setup Script for NBA Injury Risk Prediction
# =============================================================================
# Run on a fresh Ubuntu 22.04 droplet as root:
#   ssh root@YOUR_IP 'bash -s' < deploy/setup-vps.sh
#
# Or copy to the server and run:
#   scp deploy/setup-vps.sh root@YOUR_IP:~/
#   ssh root@YOUR_IP 'bash ~/setup-vps.sh'
# =============================================================================

set -euo pipefail

APP_DIR="/opt/nba-injury-scraper"
APP_USER="nba"
LOG_DIR="/var/log/nba"
DB_PASSWORD="CHANGE_ME_$(openssl rand -hex 8)"
DB_ROOT_PASSWORD="CHANGE_ME_$(openssl rand -hex 8)"

echo "============================================"
echo " NBA Injury Risk — VPS Setup"
echo "============================================"

# -------------------------------------------------------------------
# 1. System updates + basic packages
# -------------------------------------------------------------------
echo "[1/8] Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \
    curl wget git ufw fail2ban \
    ca-certificates gnupg lsb-release

# -------------------------------------------------------------------
# 2. Firewall — allow SSH, HTTP, HTTPS only
# -------------------------------------------------------------------
echo "[2/8] Configuring firewall..."
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw allow 80/tcp
ufw allow 443/tcp
ufw allow 8000/tcp   # API (remove once you set up a reverse proxy)
ufw --force enable

# -------------------------------------------------------------------
# 3. Create app user
# -------------------------------------------------------------------
echo "[3/8] Creating app user..."
if ! id "$APP_USER" &>/dev/null; then
    useradd -m -s /bin/bash "$APP_USER"
    usermod -aG docker "$APP_USER" 2>/dev/null || true
fi

# -------------------------------------------------------------------
# 4. Install Docker + docker-compose
# -------------------------------------------------------------------
echo "[4/8] Installing Docker..."
if ! command -v docker &>/dev/null; then
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    usermod -aG docker "$APP_USER"
fi

# Install docker-compose (standalone v2)
if ! command -v docker-compose &>/dev/null && ! docker compose version &>/dev/null 2>&1; then
    apt-get install -y -qq docker-compose-plugin
fi

echo "  Docker version: $(docker --version)"

# -------------------------------------------------------------------
# 5. Install Miniconda (for the nba conda environment)
# -------------------------------------------------------------------
echo "[5/8] Installing Miniconda..."
CONDA_DIR="/home/$APP_USER/miniconda3"
if [ ! -d "$CONDA_DIR" ]; then
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
    bash /tmp/miniconda.sh -b -p "$CONDA_DIR"
    rm /tmp/miniconda.sh
    chown -R "$APP_USER:$APP_USER" "$CONDA_DIR"

    # Add conda to app user's PATH
    su - "$APP_USER" -c "$CONDA_DIR/bin/conda init bash"
fi

echo "  Conda: $CONDA_DIR"

# -------------------------------------------------------------------
# 6. Set up app directory
# -------------------------------------------------------------------
echo "[6/8] Setting up app directory..."
mkdir -p "$APP_DIR"
mkdir -p "$LOG_DIR"
chown -R "$APP_USER:$APP_USER" "$APP_DIR" "$LOG_DIR"

# -------------------------------------------------------------------
# 7. Create .env file for docker-compose
# -------------------------------------------------------------------
echo "[7/8] Creating environment files..."
ENV_FILE="$APP_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# Generated by setup-vps.sh — update these values!

# Docker / MariaDB
MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
MYSQL_PASSWORD=$DB_PASSWORD

# App database URL (used by pipeline scripts)
DATABASE_URL=mysql+pymysql://nba_sql:${DB_PASSWORD}@localhost:3306/nba

# Anthropic API Key
ANTHROPIC_API_KEY=your_key_here
CLAUDE_MODEL=claude-haiku-4-5-20251001

# Twitter API (optional)
TWITTER_BEARER_TOKEN=your_twitter_bearer_token_here
TWITTER_API_KEY=your_twitter_api_key_here
TWITTER_API_SECRET=your_twitter_api_secret_here

# Reddit API (optional)
REDDIT_CLIENT_ID=your_reddit_client_id_here
REDDIT_CLIENT_SECRET=your_reddit_client_secret_here
REDDIT_USER_AGENT=nba-injury-scraper/1.0
EOF
    chown "$APP_USER:$APP_USER" "$ENV_FILE"
    chmod 600 "$ENV_FILE"
fi

# -------------------------------------------------------------------
# 8. Print next steps
# -------------------------------------------------------------------
echo ""
echo "============================================"
echo " Setup complete!"
echo "============================================"
echo ""
echo " DB password:      $DB_PASSWORD"
echo " DB root password:  $DB_ROOT_PASSWORD"
echo " App directory:     $APP_DIR"
echo " Log directory:     $LOG_DIR"
echo ""
echo " >>> SAVE THESE PASSWORDS NOW <<<"
echo ""
echo " Next steps (run from your LOCAL machine):"
echo ""
echo " 1. Push your code to the server:"
echo "    deploy/push-to-vps.sh root@YOUR_IP"
echo ""
echo " 2. SSH in and start services:"
echo "    ssh root@YOUR_IP"
echo "    cd $APP_DIR"
echo "    docker compose up -d"
echo ""
echo " 3. Set up the conda env + restore DB:"
echo "    su - $APP_USER"
echo "    cd $APP_DIR"
echo "    conda create -n nba python=3.11 -y"
echo "    conda run -n nba pip install -r requirements.txt"
echo "    conda run -n nba pip install scikit-learn lightgbm xgboost matplotlib"
echo ""
echo " 4. Restore your database (after running push-to-vps.sh):"
echo "    docker exec -i \$(docker ps -qf name=db) mysql -unba_sql -p'$DB_PASSWORD' nba < $APP_DIR/nba_dump.sql"
echo ""
echo " 5. Run migrations (creates prediction tables):"
echo "    cd $APP_DIR && conda run -n nba python main.py --migrate"
echo ""
echo " 6. Install cron jobs:"
echo "    crontab -l 2>/dev/null; cat $APP_DIR/crontab.example"
echo "    # Review, then:"
echo "    crontab $APP_DIR/crontab.example"
echo ""
echo " 7. Test:"
echo "    curl http://localhost:8000/health"
echo "    conda run -n nba python main.py --predict"
echo ""
